apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}
spec:
  selector:
    app: {{ .Values.deployment.name }}
  ports:
  - protocol: TCP
    name: http
    port: {{ .Values.service.port }}
    targetPort: {{ .Values.deployment.container.port }}
  type: {{ .Values.service.type }}
